"""Org invite links: stateless, HMAC-signed tokens — no DB table, no AWS resource.

A token just proves "this bearer was handed a link generated by an admin of
this org, before it expired" — it's not bound to a specific invitee email.
Anyone who obtains the link within its validity window can join as a plain
member. That's the accepted shape of "shareable link" (vs. an email-bound
invite); there's no revocation once issued (v1 gap, same class of tradeoff
as the ones already documented in auth_service.py).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import time
from dataclasses import dataclass

from app.core.config import settings

TOKEN_VERSION = "v1"
DEFAULT_INVITE_TTL_SECONDS = 7 * 24 * 60 * 60


class InviteTokenError(Exception):
    """Raised for an invalid, tampered, or expired invite token."""


@dataclass
class InvitePayload:
    org_slug: str
    expires_at: int


def _sign(payload: str) -> str:
    return hmac.new(settings.invite_signing_key.encode("utf-8"), payload.encode("utf-8"), hashlib.sha256).hexdigest()


def generate_invite_token(org_slug: str, ttl_seconds: int = DEFAULT_INVITE_TTL_SECONDS) -> str:
    expires_at = int(time.time()) + ttl_seconds
    # org_slug can never contain ":" (ORG_SLUG_PATTERN in models/user.py), so
    # this delimiter is safe to split on unambiguously in decode_invite_token.
    payload = f"{TOKEN_VERSION}:{org_slug}:{expires_at}"
    signature = _sign(payload)
    raw = f"{payload}:{signature}"
    return base64.urlsafe_b64encode(raw.encode("utf-8")).decode("utf-8").rstrip("=")


def decode_invite_token(token: str) -> InvitePayload:
    try:
        padded = token + "=" * (-len(token) % 4)
        raw = base64.urlsafe_b64decode(padded.encode("utf-8")).decode("utf-8")
        version, org_slug, expires_at_str, signature = raw.split(":", 3)
    except Exception as exc:
        raise InviteTokenError("This invite link is invalid.") from exc

    if version != TOKEN_VERSION:
        raise InviteTokenError("This invite link is invalid.")

    expected_signature = _sign(f"{version}:{org_slug}:{expires_at_str}")
    if not hmac.compare_digest(signature, expected_signature):
        raise InviteTokenError("This invite link is invalid.")

    expires_at = int(expires_at_str)
    if expires_at < int(time.time()):
        raise InviteTokenError("This invite link has expired.")

    return InvitePayload(org_slug=org_slug, expires_at=expires_at)
